version: '3.3'

services:

  homarr:
    image: ghcr.io/ajnart/homarr:latest 
    container_name: homarr
    restart: unless-stopped
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8200:7575'

      
